### PR TITLE
Create UML class diagrams in designs folder

### PR DESCRIPTION
**Pull request by JayKay24**
**What does this PR do?**
Add class diagrams in designs folder

**Description of Task to be Completed**
Create a class diagram of how flask will interact with the application

### CODE REVIEW

**Comment by myricoi** [comment]
well specified tests. tests passed successfully

**Comment by rnjane** [comment]
There should be a user_id in bucketlist, to identify a bucket list to a user

**Comment by luqee** [comment]
How will you identify which bucket list belongs to which user?

**Comment by JayKay24** [comment]
@luqee  I will implement a user_id attribute

**Comment by JayKay24** [comment]
I've added the user_id attribute.

**Pull request merged**
