### PR TITLE
Added a register template

### PR DESCRIPTION
**Pull request by JayKay24**
**What does this PR do?**
Add a register template and update the base template to have all subsequent templates extend from it.

**Description of task to be completed**
Implement a register view to enable user registration with the application.

**How to Test it manually**
Clone the repository using: **git clone https://github.com/JayKay24/bucket_list_app.git**
Run python main.py from the command line and navigate to register link in the navigation bar

**After-Success**
The register template is rendered in the browser

### CODE REVIEW

**Comment by rnjane** [comment]
How to test it manually, should you not start with instructions on how to clone?
Otherwise, great work. Base.html will make your code cleaner.

**Comment by JayKay24** [comment]
@rnjane I will implement instructions on how to clone in my subsequent PRs

**Comment by myricoi** [comment]
good work with linting, follow PR conventions

**Comment by JayKay24** [comment]
@rnjane I have specified how to clone the repo

**Comment by luqee** [comment]
Good work using jinja templates to create your pages.

**Comment by Mbarak-Mbigo** [comment]
Set up information should be on the README, it's not advisable to provide set up instructions on every PR you make.
Nice attempt on the PR summary

**Pull request merged**
