### PR TITLE
Add front-end UI

### PR DESCRIPTION
**Pull request by JayKay24**

### CODE REVIEW

**Comment by AwuorMarvin** [comment]
Great work man...I can see that you have been hard at work creating the UI and laying the foundation for how the app's gonna work. Good stuff.

**Comment by JayKay24** [comment]
@AwuorMarvin thanks will put in more work tomorrow.

**Comment by machariamarigi** [comment]
Good work on the wireframes and design, the application can grow from there organically.

**Comment by JayKay24** [comment]
@machariamarigi thank you. Will now move on to challenge 2

**Comment by AwuorMarvin** [comment]
@JayKay24 challenge 2?

**Pull request merged**
