### PR TITLE
Remove running tests reference from README.md

### PR DESCRIPTION
**Pull request by JayKay24**
**What does this PR do?**
Remove the description of how to run tests on the README.md

**Description of Task to be Completed**
Exclude the command to run tests from the README.md

**How should this be Manually tested?**
Change directory into the tests folder
Execution command: python -m test_all

### CODE REVIEW

**Comment by luqee** [comment]
I have reviewed your README.md. Nice specification.

**Comment by JayKay24** [comment]
@luqee  thanks. Will continue to improve.

**Comment by jmnyarega** [comment]
Nice tests, please make sure your code follows style conventions in PEP 8.

**Comment by myricoi** [comment]
I have reviewed your work. no big issues

**Comment by rnjane** [comment]
Testing your PR is wrong, consider editing it

**Pull request merged**
